apiVersion: v1
kind: Pod
metadata:
  name: drifter-sync
  labels:
    tier: api
spec:
  volumes:
    - name: drifters
      persistentVolumeClaim:
        claimName: grids    # TBD make 'drifters' PVC; currently squatting in 'grids' due to resource constraints
  containers:
  - name: schema
    imagePullPolicy: Always
    image: argovis/drifter-sync:dev
    #command: ['sleep', '1000000']
    command: ['bash', 'loaddata.sh']
    volumeMounts:
      - mountPath: "/tmp"
        name: drifters
    resources:
      requests:
        memory: "0Gi"
        cpu: "0m"
      limits:
        memory: 1Gi
        cpu: 500m
  restartPolicy: Never