apiVersion: v1
kind: Pod
metadata:
  name: drifter-roundtrip
  labels:
    tier: api
spec:
  containers:
  - name: sync
    imagePullPolicy: Always
    image: argovis/drifter-sync:roundtrip
    command: ['python', '-u', 'roundtrip.py']
    resources:
      requests:
        memory: "0Gi"
        cpu: "0m"
      limits:
        memory: 100Mi
        cpu: 100m
  restartPolicy: Never

